In [2]:
words = open("names.txt","r").read().splitlines()

In [3]:
words[:10]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn']

In [4]:
len(words)

32033

In [5]:
min(len(w) for w in words)

2

In [6]:
max(len(w) for w in words)

15

In [7]:
b = {}
for w in words:
    chs = ["<s>"] + list(w) + ["<e>"]
    for ch1, ch2 in zip(chs,chs[1:]):
        bigram = (ch1,ch2)
        b[bigram] = b.get(bigram,0) + 1

In [8]:
sorted(b.items(), key = lambda kv:-kv[1])

[(('n', '<e>'), 6763),
 (('a', '<e>'), 6640),
 (('a', 'n'), 5438),
 (('<s>', 'a'), 4410),
 (('e', '<e>'), 3983),
 (('a', 'r'), 3264),
 (('e', 'l'), 3248),
 (('r', 'i'), 3033),
 (('n', 'a'), 2977),
 (('<s>', 'k'), 2963),
 (('l', 'e'), 2921),
 (('e', 'n'), 2675),
 (('l', 'a'), 2623),
 (('m', 'a'), 2590),
 (('<s>', 'm'), 2538),
 (('a', 'l'), 2528),
 (('i', '<e>'), 2489),
 (('l', 'i'), 2480),
 (('i', 'a'), 2445),
 (('<s>', 'j'), 2422),
 (('o', 'n'), 2411),
 (('h', '<e>'), 2409),
 (('r', 'a'), 2356),
 (('a', 'h'), 2332),
 (('h', 'a'), 2244),
 (('y', 'a'), 2143),
 (('i', 'n'), 2126),
 (('<s>', 's'), 2055),
 (('a', 'y'), 2050),
 (('y', '<e>'), 2007),
 (('e', 'r'), 1958),
 (('n', 'n'), 1906),
 (('y', 'n'), 1826),
 (('k', 'a'), 1731),
 (('n', 'i'), 1725),
 (('r', 'e'), 1697),
 (('<s>', 'd'), 1690),
 (('i', 'e'), 1653),
 (('a', 'i'), 1650),
 (('<s>', 'r'), 1639),
 (('a', 'm'), 1634),
 (('l', 'y'), 1588),
 (('<s>', 'l'), 1572),
 (('<s>', 'c'), 1542),
 (('<s>', 'e'), 1531),
 (('j', 'a'), 1473),
 (

In [9]:
import torch

In [10]:
N = torch.zeros((28,28), dtype= torch.int32)

In [11]:
chars = sorted(list(set("".join(words)))) 
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi["."] = 0

In [12]:
stoi

{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26,
 '.': 0}

In [13]:
for w in words:
    chs = ["."] + list(w) + ["."]
    for ch1, ch2 in zip(chs,chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        N[ix1,ix2] += 1

In [14]:
import matplotlib.pyplot as plt
%matplotlib inline

In [15]:
itos = {i:s for s,i in stoi.items()}

In [16]:
N[0]

tensor([   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
        1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
         134,  535,  929,    0], dtype=torch.int32)

In [17]:
p = N[0].float()
p = p/p.sum()
p

tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290,
        0.0000])

In [18]:
g = torch.Generator().manual_seed(2147483647)
p = torch.rand(3 , generator=g)
p = p/p.sum()
p

tensor([0.6064, 0.3033, 0.0903])

In [19]:
torch.multinomial(p,num_samples=20, replacement = True,generator=g)

tensor([1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1])

In [20]:
P = (N+1).float()
P = P/P.sum(1 , keepdim=True)


In [21]:
g = torch.Generator().manual_seed(2147483647)

for i in range(50):
    out = []
    ix = 0
    while True:
         p = P[ix]
         #p = N[ix].float()
         #p = p/p.sum()
         ix = torch.multinomial(p,num_samples=1, replacement = True,generator=g).item()
         out.append(itos[ix])
         if ix == 0:
             break
   
    print("".join(out))


junide.
janasah.
p.
cony.
a.
nn.
kohin.
tolian.
juee.
ksahnaauranilevias.
dedainrwieta.
ssonielylarte.
faveumerifontume.
phynslenaruani.
core.
yaenon.
ka.
jabdinerimikimaynin.
anaasn.
ssorionsush.
dgossmitan.
il.
le.
pann.
that.
janreli.
isa.
dyn.
rijelumemahaunayaleva.
cararr.
jen.
janarta.
maly.
abely.
a.
i.
lavadoni.
themielyawat.
f.
modam.
tavilitikiesaloeverin.
n.
e.
kalbrenelah.
anen.
ch.
k.
jan.
odridrdenanialilpergha.
tezralelia.


In [22]:
log_likelihood = 0.0
n= 0.0
for w in words[:3]:
    chs = ["."] + list(w) + ["."]
    for ch1, ch2 in zip(chs,chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        prob = P[ix1,ix2]
        logprob = torch.log(prob)
        log_likelihood += logprob
        n+=1
        print(f"{ch1}{ch2}: {prob:.4f} {logprob:.4f}")

print(f"{log_likelihood=}")
nll = - log_likelihood
print(f"{nll=}")
print(f"{nll/n}")

.e: 0.0478 -3.0411
em: 0.0377 -3.2794
mm: 0.0253 -3.6755
ma: 0.3885 -0.9456
a.: 0.1958 -1.6305
.o: 0.0123 -4.3965
ol: 0.0779 -2.5527
li: 0.1774 -1.7294
iv: 0.0152 -4.1845
vi: 0.3506 -1.0480
ia: 0.1380 -1.9807
a.: 0.1958 -1.6305
.a: 0.1376 -1.9835
av: 0.0246 -3.7041
va: 0.2472 -1.3975
a.: 0.1958 -1.6305
log_likelihood=tensor(-38.8102)
nll=tensor(38.8102)
2.425637722015381


In [23]:
#create training set for bigrams

xs = []
ys = []
for w in words:
    chs = ["."] + list(w) + ["."]
    for ch1, ch2 in zip(chs,chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        xs.append(ix1)
        ys.append(ix2)

xs = torch.tensor(xs)
ys = torch.tensor(ys)
        

In [24]:
xs

tensor([ 0,  5, 13,  ..., 25, 26, 24])

In [25]:
ys

tensor([ 5, 13, 13,  ..., 26, 24,  0])

In [26]:
import torch.nn.functional as F
xenc = F.one_hot(xs , num_classes=27).float()
xenc

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 1., 0., 0.]])

In [27]:
xenc.shape

torch.Size([228146, 27])

In [28]:
xenc.dtype

torch.float32

In [29]:
g = torch.Generator().manual_seed(2147483647)
w = torch.randn((27,27), generator = g, requires_grad=True)
xenc @ w

tensor([[ 1.5674, -0.2373, -0.0274,  ..., -0.0707,  2.4968,  2.4448],
        [ 0.4724,  1.4830,  0.3175,  ..., -0.4275, -2.1259,  0.9604],
        [ 0.1936,  1.0532,  0.6339,  ...,  1.5447,  0.6006, -0.7091],
        ...,
        [ 0.7414, -0.5879, -0.4651,  ..., -0.1388,  1.3096, -0.2580],
        [ 1.0669,  0.2136, -0.7660,  ...,  1.3405, -0.2175,  0.8627],
        [ 0.2163, -0.7873, -0.3301,  ..., -0.2630, -0.7552,  0.8191]],
       grad_fn=<MmBackward0>)

In [78]:
for i in range(100):
    logits = xenc @ w
    counts = logits.exp()
    probs = counts/counts.sum(1,keepdim=True)
    probs

    loss = -probs[torch.arange(228146), ys].log().mean()
    print(loss.item())

    #backward pass
    w.grad = None
    loss.backward()

    #update

    w.data += -50*w.grad



2.5364670753479004
2.460636615753174
2.4580698013305664
2.457395076751709
2.457122564315796
2.4569828510284424
2.456899642944336
2.4568450450897217
2.4568068981170654
2.4567785263061523
2.456756353378296
2.4567384719848633
2.45672345161438
2.4567108154296875
2.4566993713378906
2.45668888092041
2.456679344177246
2.4566707611083984
2.45666241645813
2.4566540718078613
2.456646680831909
2.456639528274536
2.456632375717163
2.4566256999969482
2.4566190242767334
2.4566121101379395
2.456606149673462
2.4566001892089844
2.4565937519073486
2.456587791442871
2.4565820693969727
2.456576347351074
2.456570625305176
2.4565649032592773
2.456559181213379
2.4565536975860596
2.4565482139587402
2.456542730331421
2.4565372467041016
2.4565320014953613
2.456526756286621
2.4565212726593018
2.4565160274505615
2.4565110206604004
2.456505537033081
2.456500768661499
2.456495523452759
2.4564905166625977
2.4564857482910156
2.4564807415008545
2.4564757347106934
2.4564709663391113
2.4564661979675293
2.456461191177368


In [106]:
g = torch.Generator().manual_seed(3)

for i in range(5):
  
  out = []
  ix = 0
  while True:
    
    xenc = F.one_hot(torch.tensor([ix]), num_classes=27).float()
    logits = xenc @ w 
    counts = logits.exp() 
    p = counts / counts.sum(1, keepdims=True)
    # ----------
    
    ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    out.append(itos[ix])
    if ix == 0:
      break
  print(''.join(out))

cireliaha.
komeanetauma.
arouci.
slele.
jamaleniych.
